[package]
name = "generate"
version = "0.1.0"
authors = ["Kevin Stenerson <kstenerson@developers.wyyerd.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0.39"
heck = "0.3.1"
reqwest = "0.9.17"
regex = "1.1.6"
lazy_static = "1.3.0"
